-- MySQL Script generated by MySQL Workbench
-- Sun Nov  1 20:10:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`division` (
  `idDIV` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description Div` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDIV`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `idEQUIPE` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomEQUIP` VARCHAR(45) NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  `division_idDIV` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEQUIPE`, `division_idDIV`),
  CONSTRAINT `fk_equipe_division1`
    FOREIGN KEY (`division_idDIV`)
    REFERENCES `mydb`.`division` (`idDIV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`maillot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maillot` (
  `idMAILLOT` INT NOT NULL,
  `couleur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMAILLOT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`POSTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`POSTE` (
  `idPoste` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPoste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`joueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`joueur` (
  `idJR` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomJR` VARCHAR(45) NOT NULL,
  `equipe_idEQUIPE` INT UNSIGNED NOT NULL,
  `maillot_idMAILLOT` INT NOT NULL,
  `age` INT NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `POSTE_idPoste` INT UNSIGNED NOT NULL,
  `photo-url` VARCHAR(45) NOT NULL,
  `nationalité` VARCHAR(45) NULL,
  PRIMARY KEY (`idJR`, `equipe_idEQUIPE`, `maillot_idMAILLOT`, `POSTE_idPoste`),
  CONSTRAINT `fk_joueur_equipe`
    FOREIGN KEY (`equipe_idEQUIPE`)
    REFERENCES `mydb`.`equipe` (`idEQUIPE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joueur_maillot1`
    FOREIGN KEY (`maillot_idMAILLOT`)
    REFERENCES `mydb`.`maillot` (`idMAILLOT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joueur_POSTE1`
    FOREIGN KEY (`POSTE_idPoste`)
    REFERENCES `mydb`.`POSTE` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
